# Generated by Django 2.0.2 on 2020-07-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20200715_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_id', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=50)),
                ('user_screen_name', models.CharField(max_length=50)),
            ],
        ),
    ]
