# Generated by Django 2.0.2 on 2020-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qiita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.IntegerField()),
                ('icon_url', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=20)),
                ('items_count', models.IntegerField()),
            ],
        ),
    ]
