# Generated by Django 2.0.2 on 2020-07-20 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_qiita'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
