# Generated by Django 2.0.2 on 2020-07-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_boardmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
