# Generated by Django 2.0.2 on 2020-07-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_auto_20200721_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='date',
        ),
    ]
