# Generated by Django 2.0.2 on 2020-07-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0008_remove_boardmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
